qlib_init:
    provider_uri: "../qlib_data/qlib_bin"
    region: cn
market: &market all
benchmark: &benchmark 000300.sh
data_handler_config: &data_handler_config
    start_time: 2023-01-01
    end_time: 2026-01-08
    fit_start_time: 2023-01-01
    fit_end_time: 2025-12-31
    instruments: *market
    
port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal: <PRED>
            topk: 50
            n_drop: 5
            risk_degree: 1.0
    backtest:
        start_time: 2026-01-07
        end_time: 2026-01-08
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5
            trade_unit: 1
task:
    experiment_name: "test_lgbm"
    model:
        class: LGBModel
        module_path: qlib.contrib.model.gbdt
        kwargs:
            loss: mse
            colsample_bytree: 0.7719977776954766
            learning_rate: 0.07898892598431795
            subsample: 0.6895633934838533
            lambda_l1: 8.780103579048659e-06
            lambda_l2: 1.1381108970595143e-08
            num_leaves: 27
            feature_fraction: 0.5566228049605826
            bagging_fraction: 0.40015270709406303
            bagging_freq: 3
            min_data_in_leaf: 29
            min_child_samples: 54
            max_depth: 10
    dataset:
        class: DatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: Alpha158
                module_path: qlib.contrib.data.handler
                kwargs: *data_handler_config
            segments:
                train: [2023-01-01, 2025-12-31]
                valid: [2026-01-05, 2026-01-06]
                test: [2026-01-07, 2026-01-08]
    record: 
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            model: <MODEL>
            dataset: <DATASET>
      
       
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            config: *port_analysis_config
