type: "mysql"

port: 3306

chunk_size: 20000
workers: 4

host: "localhost:3306"

database: "data_prepared_new"

user: "your_username"
password: "your_password"

table_name: "data_score"

database2: "portfolio_new"

table_name2: "portfolio"
table_name4: "portfolio_info"
table_name5: "portfolio_info"
table_name6: "portfolio_constraint"
table_name7: "factor_constraint"

host2: "localhost:3306"

database3: "data_prepared_new"

host3: "localhost:3306"

database4: "qlib"

user2: "your_username"

table_name3: "best_params"
