base_dir: "E:\\qlib_data"

# 存放csv版本所需要的数据
csv_output_dir: "${base_dir}\\csv_data"
# 存放每日更新需要的csv版本数据
csv_daily_dir: "${base_dir}\\daily"

# 存放qlib二进制数据的路径
provider_uri: "${base_dir}\\qlib_bin"

#克隆之后qlib库的存放路径
qlib_workdir: "E:\\qlib" 

# 训练好的模型存放路径
# model_path: "E:\\qlib_data\\output\\mlruns\\791798094765178125\\21ab91807eff4e61bee33331ff1c4411\\artifacts\\trained_model"
model_path: "E:\\qlib-optimizer\\2025\\trained_model"

# 预测出的score文件存放路径
prediction_output_dir: "${base_dir}\\output\\prediction"


# 临时存放合并后的优化后的权重文件
temp_dir: "${base_dir}\\temp"


# 输出的优化结果存放路径
processing_data_dir: "${base_dir}\\processing"
# 模型配置文件路径
yaml_path: "..\\qlib_code\\workflow_config_lightgbm.yaml"

# python 执行路径
python_exe: "E:\\ProgramData\\anaconda3\\envs\\new_qlib_env\\python.exe"

yaml_matlab: "..\\YAMLMatlab_0.4.3"

global_tools: "GLOBAL_TOOLSFUNC_test"





