base_dir: "../qlib_data"

csv_output_dir: "${base_dir}/csv_data"

csv_daily_dir: "${base_dir}/daily"

provider_uri: "${base_dir}/qlib_bin"

qlib_workdir: "./qlib"

model_path: "./models/trained_model"

prediction_output_dir: "${base_dir}/output/prediction"

temp_dir: "${base_dir}/temp"

processing_data_dir: "${base_dir}/processing"

yaml_path: "./qlib_code/workflow_config_lightgbm.yaml"

python_exe: "python"

yaml_matlab: "./YAMLMatlab_0.4.3"

global_tools: "GLOBAL_TOOLSFUNC_new"
